# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=32, verbose_name='集群/组')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ManyToManyField(to='monitor.HostGroup', verbose_name='集群/组'),
        ),
    ]
