# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(choices=[('max', 'Max'), ('min', 'Min'), ('average', 'Average')], max_length=16, verbose_name='统计方法')),
                ('condition', models.CharField(choices=[('gt', '大于'), ('lt', '小于'), ('eq', '等于'), ('gte', '大于等于'), ('lte', '小于等于')], max_length=16, verbose_name='运算符')),
                ('limit_value', models.IntegerField(verbose_name='阀值')),
                ('logic_type', models.CharField(blank=True, choices=[('or', 'OR'), ('and', 'AND')], max_length=32, null=True, verbose_name='与下一个条件的逻辑关系')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.HostGroup', verbose_name='集群/组')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Indicator', verbose_name='指标参数')),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('Online', '在线'), ('Offline', '掉线'), ('Maintenance', '维护')], max_length=64, verbose_name='状态'),
        ),
    ]
