# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20160930_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='指标组名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='group',
            field=models.ManyToManyField(to='monitor.IndicatorGroup', verbose_name='指标组'),
        ),
    ]
