# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20160930_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='group',
        ),
        migrations.AddField(
            model_name='indicatorgroup',
            name='indicator',
            field=models.ManyToManyField(to='monitor.Indicator', verbose_name='指标'),
        ),
    ]
