# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20160930_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='告警')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmUpgradeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_times', models.IntegerField(verbose_name='告警次数')),
                ('mail_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.UserProfile', verbose_name='发送给')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmUpgradeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='告警升级模版')),
                ('upgrade_items', models.ManyToManyField(to='monitor.AlarmUpgradeItem', verbose_name='告警升级条目')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(choices=[('max', 'Max'), ('min', 'Min'), ('average', 'Average')], max_length=16, verbose_name='统计方法')),
                ('condition', models.CharField(choices=[('gt', '大于'), ('lt', '小于'), ('eq', '等于'), ('gte', '大于等于'), ('lte', '小于等于')], max_length=16, verbose_name='运算符')),
                ('limit_value', models.IntegerField(verbose_name='阀值')),
                ('logic_type', models.CharField(blank=True, choices=[('or', 'OR'), ('and', 'AND')], max_length=32, null=True, verbose_name='与下一个条件的逻辑关系')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.HostGroup', verbose_name='集群/组')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Indicator', verbose_name='指标参数')),
            ],
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='func',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='group',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='limit_value',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='logic_type',
        ),
        migrations.AddField(
            model_name='trigger',
            name='level',
            field=models.CharField(choices=[('info', '消息'), ('debug', '调试'), ('danger', '危险'), ('disaster', '灾难')], default=123, max_length=16, verbose_name='事件级别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trigger',
            name='name',
            field=models.CharField(default=123, max_length=16, verbose_name='触发器名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarm',
            name='alarm_upgrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.AlarmUpgradeTemplate', verbose_name='告警级别升级模版'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='triggers',
            field=models.ManyToManyField(to='monitor.Trigger', verbose_name='触发器'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='triggeritems',
            field=models.ManyToManyField(to='monitor.TriggerItem', verbose_name='触发器条目'),
        ),
    ]
