# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-30 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20160930_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='host',
            name='username',
            field=models.CharField(blank=True, default='root', max_length=32, null=True, verbose_name='用户名'),
        ),
    ]
